vich_uploader:
  db_driver: orm

  mappings:
    medias:
      uri_prefix: /medias/images
      upload_destination: "%kernel.project_dir%/public/medias/images"

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
